project:
  type: website

website:
  title: "ISSS626-GAA"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Exercise 1: Geospatial Data"
            href: "Hands-on_Ex/Hands-on_Ex01/chap01.html"
          - text: "Exercise 1: Thematic Mapping"
            href: "Hands-on_Ex/Hands-on_Ex01/chap02.html"
          - text: "Exercise 2: Point Density"
            href: "Hands-on_Ex/Hands-on_Ex02/chap04.html"
          - text: "Exercise 2: Point Interaction"
            href: "Hands-on_Ex/Hands-on_Ex02/chap05.html"
      - about.qmd
    right:
      - icon: github
        href: https://github.com/sabrinahao99/ISSS626-GEO
      - href: index.qmd
        text: Home
  page-footer:
    center: "ISSS626 Geospatial Analytics and Applications coursework"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 4
    number-sections: true
    code-copy: true
    code-overflow: wrap
    fig-align: center

editor: visual
